export class Formulario2{
    constructor(
        public id:number,
        public fecha:string,
        public nombre:string,
        public sexo:string,
        public celular:string,
        public poblacion:string,
        public poblacion1:string,
        //interrogatorio
        public enfermedades:string,
        public diagnosticos:string,
        public penicilina:string,
        public pen_otros:string,
        public pen_cuales:string,
        public anestesia:string,
        public prom_anestesia:string,
        public des_anestesia:string,
        public sangra:string,
        public hemorragia:string,
        public usa_anti:string,
        public usa_tranqui:string,
        //public usa_tranqui_descrip:string,
        public otros_med:string,
        public otros_med_des:string,
        public diabetico:string,
        public par_cual:string,
        //exploracion
        public cara:string,
        public blando:string,
        public duro:string,
        public labios:string,
        public boca:string,
        public cuello:string,
        public salivales:string,
        public carrillos:string,
        public lengua:string,
        public amigdalas:string,
        //odontograma
        public dDS18:string,
        public dDS17:string,
        public dDS16:string,
        public dDS15:string,
        public dDS14:string,
        public dDS13:string,
        public dDS12:string,
        public dDS11:string,
        public dDS55:string,
        public dDS54:string,
        public dDS53:string,
        public dDS52:string,
        public dDS51:string,
        public dIS28:string,
        public dIS27:string,
        public dIS26:string,
        public dIS25:string,
        public dIS24:string,
        public dIS23:string,
        public dIS22:string,
        public dIS21:string,
        public dIS65:string,
        public dIS64:string,
        public dIS63:string,
        public dIS62:string,
        public dIS61:string,
        public dDI48:string,
        public dDI47:string,
        public dDI46:string,
        public dDI45:string,
        public dDI44:string,
        public dDI43:string,
        public dDI42:string,
        public dDI41:string,
        public dDI85:string,
        public dDI84:string,
        public dDI83:string,
        public dDI82:string,
        public dDI81:string,
        public dII38:string,
        public dII37:string,
        public dII36:string,
        public dII35:string,
        public dII34:string,
        public dII33:string,
        public dII32:string,
        public dII31:string,
        public dII75:string,
        public dII74:string,
        public dII73:string,
        public dII72:string,
        public dII71:string,

    )
    {}
}