export class Formulario1{
    constructor(
        public id:string,
        public Iask1:number,
        public iask2:number,
        public iask3:number,
        public iask31:string,
        public iask4:number,
        public iask41:string,
        public iask42:string,
        public iask43:string,
        public Iask5:number,

        public IIask7:number,
        public IIask8:number,
        public IIask9:number,
        public IIask10:number,
        public IIask11:number,
        public IIask12:number,
        public IIask13:number,
        public IIask14:number,
        public IIask15:number,
        public IIask16:number,
        public IIask17:number,
        public IIask18:number,
        public IIask19:number,
        public IIask20:number,
        public IIask21:number,
        public IIask22:number,
        public IIask23:number,
        public IIask24:number,
        public IIask25:number,
        public IIask26:number,
        public IIask27:number,
        public IIask28:number,
        
        public IIIask29:number,
        public IIIask30:number,
        public IIIask31:number,
        public IIIask32:number,
        public IIIask33:number,
        public IIIask34:number,
        public IIIask35:number,
        public IIIask36:number,
        public IIIask37:number,
        public IIIask38:number,
        public IIIask39:number,
        public IIIask40:number,
        public IIIask41:number,
        public IIIask42:number,
        public IIIask43:number,
        public IIIask44:number,
        public IIIask45:number,
        public IIIask46:number,
        public IIIask47:number,
        public IIIask48:number,
        public IIIask49:number,
        public IIIask50:number,

        public IVask51:number,
        public IVask52:number,
        public IVask53:number,
        public IVask54:number,
        public IVask55:number,
        public IVask56:number,
        public IVask57:number,
        public IVask58:number,
        public IVask59:number,
        public IVask60:number,

        public Vask61:number,
        public Vask62:number,
        public Vask63:number,
        public Vask64:number,
        public Vask641:string,

        public VIask65:number,
        public VIask66:number,

        public VIIask67:string,
        public VIIask671:string,

        public firma:string,
        public fecha2:string

    )
    {}
}