export class FormularioAtm{
    constructor(
        public ATMMov_Mand_Dim_Aper:string,
        public ATMMov_Mand_Dim_Vert1:string,
        public ATMMov_Mand_Dim_Vert2:string,
        public ATMMov_Mand_Desv_Mand_Apertura:string,
        public ATMMov_Mand_Desv_Mand_Cierre:string,
        public ATMR_Art_Chasquido:string,
        public ATMR_Art_Apertura:string,
        public ATMR_Art_Cierre:string,
        public ATMR_Art_Der:string,
        public ATMR_Art_Izq:string, 
        public ATMR_Art_Bilateral:string,
        public ATMR_Art_Inicial:string,
        public ATMR_Art_Medio:string,
        public ATMR_Art_Tardio:string,
        public ATMR_Art_Reciproco:string, 
        public ATMCrepitacion:string,
        public ATMCrep_Der:string,
        public ATMCrep_Izq:string,
        public ATMCrep_Bi:string,
        public ATMLuxacion:string,
        public ATMLux_Der:string,
        public ATMLux_Izq:string,
        public ATMLux_Bi:string,
        public ATMDolor:string,
        public ATMDolor_Der:string, 
        public ATMDolor_Izq:string,
        public ATMDolor_Bi:string,
        public ATMSDP:string,
        public ATMCuadrantesD1:string,
        public ATMCuadrantesD2:string,
        public ATMCuadrantesD3:string,
        public ATMCuadrantesD4:string,
        public ATMDentariosD1:string,
        public ATMDentariosD2:string,
        public ATMDentariosD3:string,
        public ATMDentariosD4:string,
        public firma:string,

    )
    {}
}