export class Formulario1{
    constructor(
        public Id_Pacient:string,
        public Iask1:string,
        public iask2:string,
        public iask3:string,
        public iask31:string,
        public iask4:string,
        public iask41:string,
        public iask42:string,
        public iask43:string,
        public Iask5:string,

        public IIask7:string,
        public IIask8:string,
        public IIask9:string,
        public IIask10:string,
        public IIask11:string,
        public IIask12:string,
        public IIask13:string,
        public IIask14:string,
        public IIask15:string,
        public IIask16:string,
        public IIask17:string,
        public IIask18:string,
        public IIask19:string,
        public IIask20:string,
        public IIask21:string,
        public IIask22:string,
        public IIask23:string,
        public IIask24:string,
        public IIask25:string,
        public IIask26:string,
        public IIask27:string,
        public IIask28:string,
        
        public IIIask29:string,
        public IIIask30:string,
        public IIIask31:string,
        public IIIask32:string,
        public IIIask33:string,
        public IIIask34:string,
        public IIIask35:string,
        public IIIask36:string,
        public IIIask37:string,
        public IIIask38:string,
        public IIIask39:string,
        public IIIask40:string,
        public IIIask41:string,
        public IIIask42:string,
        public IIIask43:string,
        public IIIask44:string,
        public IIIask45:string,
        public IIIask46:string,
        public IIIask47:string,
        public IIIask48:string,
        public IIIask49:string,
        public IIIask50:string,

        public IVask51:string,
        public IVask52:string,
        public IVask53:string,
        public IVask54:string,
        public IVask55:string,
        public IVask56:string,
        public IVask57:string,
        public IVask58:string,
        public IVask59:string,
        public IVask60:string,

        public Vask61:string,
        public Vask62:string,
        public Vask63:string,
        public Vask64:string,
        public Vask641:string,

        public VIask65:string,
        public VIask66:string,

        public VIIask67:string,
        public VIIask671:string,

        public firma:string,
        public fecha2:string

    )
    {}
}