export class Odontograma{
    constructor(
        //odontograma
        public Id_Pacient:string,
        public dDS18:number,
        public dDS17:number,
        public dDS16:number,
        public dDS15:number,
        public dDS14:number,
        public dDS13:number,
        public dDS12:number,
        public dDS11:number,
        public dDS55:number,
        public dDS54:number,
        public dDS53:number,
        public dDS52:number,
        public dDS51:number,
        public dIS28:number,
        public dIS27:number,
        public dIS26:number,
        public dIS25:number,
        public dIS24:number,
        public dIS23:number,
        public dIS22:number,
        public dIS21:number,
        public dIS65:number,
        public dIS64:number,
        public dIS63:number,
        public dIS62:number,
        public dIS61:number,
        public dDI48:number,
        public dDI47:number,
        public dDI46:number,
        public dDI45:number,
        public dDI44:number,
        public dDI43:number,
        public dDI42:number,
        public dDI41:number,
        public dDI85:number,
        public dDI84:number,
        public dDI83:number,
        public dDI82:number,
        public dDI81:number,
        public dII38:number,
        public dII37:number,
        public dII36:number,
        public dII35:number,
        public dII34:number,
        public dII33:number,
        public dII32:number,
        public dII31:number,
        public dII75:number,
        public dII74:number,
        public dII73:number,
        public dII72:number,
        public dII71:number,
        public c1:number,
        public p1:number,
        public o1:number,
        public cpo:number,
        public Obser:string

    )
    {}
}